import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
// import { Inter } from "@next/font/google";
// import styles from "@/styles/Home.module.css";

// const inter = Inter({ subsets: ["latin"] });

import { Amplify, API, graphqlOperation } from "aws-amplify";
import awsconfig from "../aws-exports";

import { createTodo, updateTodo, deleteTodo } from "../graphql/mutations";
import { listTodos } from "../graphql/queries";

Amplify.configure(awsconfig);

export default function Home() {
  const [newThingTodo, setNewThingTodo] = useState("");
  const [todoList, setTodoList] = useState([]);

  const onSubmit = async (e) => {
    e.preventDefault();

    const result = await API.graphql(
      graphqlOperation(createTodo, {
        input: {
          name: newThingTodo,
        },
      })
    );

    todoList.push(result.data.createTodo);
    setTodoList(todoList);
    setNewThingTodo("");
  };

  const getList = async () => {
    try {
      const results = await API.graphql(graphqlOperation(listTodos));
      setTodoList(results.data.listTodos.items);
    } catch (error) {
      console.log(error);
    }
  };

  useEffect(() => {
    getList();
  }, []);

  const onDelete = async (id) => {
    try {
      const result = await API.graphql(
        graphqlOperation(deleteTodo, {
          input: {
            id,
          },
        })
      );

      const filterTodo = todoList.filter((todo) => todo.id !== id);
      setTodoList(filterTodo);
    } catch (error) {
      console.log(error);
    }
    console.log(`deleteing... ${id}`);
  };

  return (
    <>
      <main>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Image
          // className={styles.logo}
          src="/image/rbt.jpg"
          alt="robotics"
          width={300}
          height={150}
          priority
        />

        <div>
          <h2>Thing(s) todo</h2>
          <form onSubmit={onSubmit}>
            <input
              value={newThingTodo}
              onChange={(e) => setNewThingTodo(e.target.value)}
            />
            <button type="submit">Add</button>
          </form>

          <ul>
            {todoList.map(({ id, name }) => (
              <li key={id}>
                {name} - <button onClick={() => onDelete(id)}>Delete</button>
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
}
